# Site settings
title: wwwtf.amsterdam – Amsterdam, October 2017
description: "wwwtf.amsterdam is a collection of fine events around the web, happening in Amsterdam in October 2017"
baseurl: ""
url: https://wwwtf.amsterdam   # with the https protocol
enforce_ssl: wwwtf.amsterdam   # without any protocol
exclude:
  - README.md

# Build settings
markdown: kramdown
permalink: pretty

# Site data
github_repo: "pverbeek/wwwtf.amsterdam"
twitter_username: wwwtfamsterdam
