# Site settings
title: wwwtf.berlin – Berlin, May-June 2018
description: "wwwtf.berlin is a collection of fine events around the web, happening in Berlin in May and June 2018"
baseurl: ""
url: "http://wwwtf.berlin"
exclude:
  - README.md

# Build settings
markdown: kramdown
permalink: pretty

# Site data
github_repo: "janl/wwwtf.berlin"
twitter_username: wwwtfberlin
future: true
